[project]
id = "mqtt"
version = "0.1.0"
src = "src"
out = "out/{target.name}/{profile.name}"

[target.linux-x86_64]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[target.linux-arm64]
isa = "aarch64"
os  = "linux"
abi = "aapcs64"

[profile.debug]
opt = 0
debug = true

[profile.release]
opt = 2
debug = false

[artifact.mqtt]
kind = "static"
entry = "lib.mach"
out = "lib/mqtt"
targets = ["*"]
link = []
need = []

[artifact.brokerd]
kind = "bin"
entry = "bin/brokerd.mach"
out = "bin/brokerd"
targets = ["*"]
link = []
need = []

[dep.mach-std]
git = "https://github.com/briar-systems/mach-std"
ref = "branch/main"
